const express=require('express')
const router=express.Router()
const UserController=require('../app/controllers/UserController')
const StoreController=require('../app/controllers/StoreController')
const MenuCategoryController=require('../app/controllers/MenuCategoryController')
const MenuItemController=require('../app/controllers/MenuItemController')
const OrderController=require('../app/controllers/OrderController')
const { authenticateUser, authenticateStore,authorizeUser}=require('../app/middlewares/authenticate')

router.post('/api/user/register', UserController.register)
router.post('/api/user/login', UserController.login)
router.get('/api/user/account', authenticateUser, UserController.account)

router.post('/api/store/create',authenticateUser,authorizeUser,StoreController.create)
router.post('/api/store/login',StoreController.login)
router.get('/api/store/show',authenticateUser,authorizeUser,StoreController.show)
router.get('/api/store/showOne',authenticateStore,StoreController.showOne)
router.put('/api/store/update',authenticateStore,StoreController.update)
router.delete('/api/store/delete/:storeId',authenticateStore,StoreController.delete)

router.post('/api/menuCategory/create',authenticateStore,MenuCategoryController.create)
router.get('/api/menuCategory/show/:storeId',authenticateUser,authorizeUser,MenuCategoryController.show)
router.get('/api/menuCategory/showOne',authenticateStore,MenuCategoryController.showOne)
router.get('/api/menuCategory/showDeleted',authenticateStore,MenuCategoryController.showDeleted)
router.delete('/api/menuCategory/delete/:id',authenticateStore,MenuCategoryController.delete)
router.delete('/api/menuCategory/softDelete/:id',authenticateStore,MenuCategoryController.softDelete)
router.delete('/api/menuCategory/restore/:id',authenticateStore,MenuCategoryController.restore)
                
router.post('/api/menuItem/create',authenticateStore,MenuItemController.create)
router.get('/api/menuItem/show/:storeId',authenticateUser,authorizeUser,MenuItemController.show)
router.get('/api/menuItem/showDeleted',authenticateStore,MenuItemController.showDeleted)
router.get('/api/menuItem/showOne',authenticateStore,MenuItemController.showOne)
router.get('/api/menuItem/showFiltered/:categoryId',authenticateStore,MenuItemController.showfiltered)
router.get('/api/menuItem/showSearched/:str',authenticateStore,MenuItemController.showSearched)
router.put('/api/menuItem/update/:id',authenticateStore,MenuItemController.updateMenuItem)
router.delete('/api/menuItem/delete/:id',authenticateStore,MenuItemController.delete)
router.delete('/api/menuItem/softDelete/:id',authenticateStore,MenuItemController.softDelete)
router.delete('/api/menuItem/restore/:id',authenticateStore,MenuItemController.restore)

router.post('/api/order/create',authenticateStore,OrderController.create)
router.get('/api/order/showAll/:storeId',authenticateUser,authorizeUser,OrderController.showAll)
router.get('/api/order/showAdminOrder/:storeId',authenticateUser,authorizeUser,OrderController.showAdminOrderCompleted)
router.get('/api/order/showByStore',authenticateStore,OrderController.showByStore)
router.get('/api/order/showCompleted',authenticateStore,OrderController.showCompleted)
router.put('/api/order/update/:id',authenticateStore,OrderController.update)
router.delete('/api/order/softDelete/:id',authenticateStore,OrderController.softDelete)
router.delete('/api/order/delete',authenticateStore,OrderController.delete)

module.exports=router